services:
  - type: web
    name: bot-halaqah
    env: python
    buildCommand: ""
    startCommand: "python bot_halaqah.py"
    envVars:
      - key: BOT_TOKEN
        value: "ISI_TOKEN_BOT_MU"
      - key: WEBHOOK_URL
        value: "https://bot-halaqah.onrender.com/webhook"
      - key: GOOGLE_CREDS_JSON
        value: "ISI_ISI_JSON_GOOGLE_ESCAPED"
